/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Health
     * @description Report which inference subsystems are ready, which adapters are bound,
     *     and the active TTS adapter's capability metaconfig.
     */
    get: operations["get_health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/voices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Voices
     * @description List the voice ids the active TTS engine accepts.
     *
     *     Shape: ``{"voices": ["<id>", …]}``. Engine-specific — Kokoro returns
     *     ``af_*`` / ``am_*`` ids. Engines without a named catalog
     *     (``tts_features.named_voices`` false) may return a single sentinel id.
     */
    get: operations["get_voices_voices_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/synthesize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Synthesize
     * @description Synthesize speech from text using the active TTS engine.
     *
     *     **Response:** ``audio/wav`` bytes (HTTP 200). Returns 503 when TTS isn't loaded.
     *
     *     Declared ``async`` even though :meth:`TtsEngine.synthesize` is sync so the
     *     call runs on the asyncio loop thread (where lifespan loaded the weights)
     *     rather than a worker thread. CPU backends (Kokoro) don't care, but
     *     GPU/accelerator backends that pin their compute stream to the loading
     *     thread would otherwise fault — keeping this ``async`` is the safe default.
     */
    post: operations["synthesize_synthesize_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/transcribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Transcribe
     * @description Transcribe uploaded audio to text and language metadata.
     *
     *     **Response:** JSON ``{text, language, probability}``. Returns 503 if STT is unavailable.
     */
    post: operations["transcribe_transcribe_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/shutdown": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Shutdown
     * @description Hard-kill the sidecar from another shell when SIGINT is wedged.
     *
     *     A long-running native generation can block the Python interpreter for its
     *     whole duration, so SIGINT queues until the gen finishes — and on
     *     pathological inputs that's never. Hitting this route schedules
     *     ``os._exit(0)`` on a short delay so the HTTP response can flush first,
     *     then bypasses the interpreter shutdown machinery entirely.
     *
     *     Trigger it with::
     *
     *         curl -XPOST http://127.0.0.1:8000/shutdown
     */
    post: operations["shutdown_shutdown_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_transcribe_transcribe_post */
    Body_transcribe_transcribe_post: {
      /**
       * File
       * @description Audio upload (e.g. WAV). Transcribed with the active STT engine (``faster-whisper small.en`` by default).
       */
      file: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description JSON body for ``GET /health``.
     */
    HealthResponse: {
      /**
       * Tts
       * @description TTS engine status: ``ready`` or ``unavailable``.
       */
      tts: string;
      /**
       * Stt
       * @description STT engine status: ``ready`` or ``unavailable``.
       */
      stt: string;
      /**
       * Tts Backend
       * @description Name of the loaded TTS adapter (e.g. ``kokoro``); ``null`` when unavailable.
       */
      tts_backend?: string | null;
      /**
       * Stt Backend
       * @description Name of the loaded STT adapter (e.g. ``whisper``); ``null`` when unavailable.
       */
      stt_backend?: string | null;
      /** @description Capability metaconfig of the active TTS adapter; ``null`` when TTS is unavailable. Apps render controls conditionally off these. */
      tts_features?: components["schemas"]["TtsFeaturesResponse"] | null;
    };
    /**
     * SynthesizeRequest
     * @description JSON body for ``POST /synthesize``.
     *
     *     Produces a WAV-encoded audio stream from the configured TTS engine. Voice
     *     id and sample rate are engine-specific — see ``GET /voices`` for the
     *     active catalog. Default voice on Kokoro is ``af_aoede``.
     */
    SynthesizeRequest: {
      /**
       * Text
       * @description Plain text to speak.
       */
      text: string;
      /**
       * Voice
       * @description Engine-specific voice id. Kokoro accepts ``af_*`` / ``am_*`` ids. Engines without a named catalog (``tts_features.named_voices`` false) ignore this. See ``GET /voices``.
       * @default af_aoede
       */
      voice: string;
      /**
       * Speed
       * @description Speaking-rate multiplier (1.0 = engine default). Engines without a speed knob (``tts_features.speed`` false) ignore this field silently.
       * @default 1
       */
      speed: number;
      /** @description Optional reference-audio voice clone. Consumed only by engines whose ``tts_features.cloning`` is true; other engines ignore it. */
      reference?: components["schemas"]["VoiceReferenceBody"] | null;
    };
    /**
     * TtsFeaturesResponse
     * @description Capability flags the active TTS adapter advertises (see
     *     :class:`ports.TtsFeatures`). Apps read these to render only the controls a
     *     backend honours — the voice-reference panel keys off ``cloning``, the speed
     *     slider off ``speed``, the voice picker off ``named_voices``.
     */
    TtsFeaturesResponse: {
      /**
       * Cloning
       * @description Engine honours the ``reference`` field for voice cloning.
       */
      cloning: boolean;
      /**
       * Speed
       * @description Engine honours the ``speed`` multiplier.
       */
      speed: boolean;
      /**
       * Named Voices
       * @description Engine exposes a catalog of named voice ids via ``GET /voices``.
       */
      named_voices: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VoiceReferenceBody
     * @description Reference-audio voice conditioning. Only engines whose
     *     ``tts_features.cloning`` is true consume this; others ignore it silently.
     */
    VoiceReferenceBody: {
      /**
       * Audio Path
       * @description Absolute filesystem path to a short reference WAV (5-10s typical). The server must have read access; the daemon and the client need to live on the same machine for this path to resolve.
       */
      audio_path: string;
      /**
       * Transcript
       * @description Exact transcript of the reference audio. Helps the model disentangle voice characteristics from textual content.
       */
      transcript: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  get_voices_voices_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  synthesize_synthesize_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SynthesizeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transcribe_transcribe_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_transcribe_transcribe_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  shutdown_shutdown_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
