/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/voices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Voices
     * @description List American English Kokoro v1 voice ids.
     *
     *     Returns ``application/json`` with a ``voices`` array of strings (``af_*``, ``am_*``)
     *     for **hexgrad/Kokoro-82M** when using ``lang_code=a`` in the pipeline.
     */
    get: operations["get_voices_voices_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/synthesize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Synthesize
     * @description Synthesize speech from text using the loaded Kokoro pipeline.
     *
     *     **Response:** ``audio/wav`` bytes (HTTP 200). Returns 503 if the TTS model failed to load.
     */
    post: operations["synthesize_synthesize_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/transcribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Transcribe
     * @description Transcribe uploaded audio to text (and language metadata).
     *
     *     **Response:** JSON with ``text``, ``language``, and ``probability``. Returns 503 if STT is unavailable.
     */
    post: operations["transcribe_transcribe_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_transcribe_transcribe_post */
    Body_transcribe_transcribe_post: {
      /**
       * File
       * Format: binary
       * @description Audio upload (e.g. WAV). Transcribed with faster-whisper ``base.en`` when the STT model loaded at startup.
       */
      file: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * SynthesizeRequest
     * @description JSON body for ``POST /synthesize``.
     *
     *     Produces linear PCM in a WAV container via Kokoro 82M (``hexgrad/Kokoro-82M``, ``lang_code=a``).
     */
    SynthesizeRequest: {
      /**
       * Text
       * @description Plain text to speak.
       */
      text: string;
      /**
       * Voice
       * @description Kokoro v1 voice id (American English: ``af_*`` / ``am_*``). See ``GET /voices`` for the supported list.
       * @default af_aoede
       */
      voice: string;
      /**
       * Speed
       * @description Speaking-rate multiplier (1.0 = model default).
       * @default 1
       */
      speed: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_voices_voices_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  synthesize_synthesize_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SynthesizeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transcribe_transcribe_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_transcribe_transcribe_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
